apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboardproviders
  namespace: testapp
data:
  dashboardproviders.yaml: |-
    apiVersion: 1

    providers:
      - name: default
        disableDeletion: false
        editable: true
        folder: ""
        orgId: 1
        type: file
        options:
          path: /var/lib/grafana/dashboards
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: testapp
data:
  datasource.yaml: |-
    apiVersion: 1

    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus:9090
        version: 1
        isDefault: true
   
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana
    version: "1.0"
  name: grafana
  namespace: testapp
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: grafana
      version: "1.0"
  template:
    metadata:
      labels:
        app: grafana
        version: "1.0"
    spec:
      securityContext:
        runAsUser: 472
        fsGroup: 472
      containers:
        - name: grafana
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: admin
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: value
          image: grafana/grafana:8.3.3
          ports:
            - name: grafana
              protocol: TCP
              containerPort: 3000
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: grafana-pv
            - mountPath: /etc/grafana/provisioning/datasources
              name: grafana-datasources
            - name: grafana-dashboardproviders
              mountPath: "/etc/grafana/provisioning/dashboards/"
            
          resources:
            limits:
              memory: 256Mi
      volumes:
        - name: grafana-pv
          persistentVolumeClaim:
            claimName: grafana-pvc
        - name: grafana-datasources
          configMap:
            defaultMode: 420
            name: grafana-datasources
        - name: grafana-dashboardproviders
          configMap:
            name: grafana-dashboardproviders
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: testapp
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
    - port: 3000
      targetPort: 3000
