apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-credentials
  namespace: customer
spec:
  encryptedData:
    admin-password: AgCzQIY0jRediNm4u6uIjhqluqBMMmQnnGPFPjcMSgac+8dsb6j5pwyYcqOUeDi6aGjWBYQMCvab0ldMqu2Xmc1b40ci79hej+nLNPbDi3YgbpcN1BYMFuerjR5EkPfjGGYGLXZhNQGeQ3xG8njjPMdSb8G50k9f4/10lb8UM+xa6GfA3EPfTRsooUKu9jM9Q8EPxhzJXMD6Ce0DhCBf5sT/NTFN7KHCBN2Iu+OXuD+HjFtt7ae3p67IBVfnD5xMaWkysGi/dwyxbTy8q86heyOY17DkBjS3ZR0bnplEAJWZQpCZ/TF2JZdEbRrZJLkgBdPacAYKBdCUw+80vzF9DgzIO81Fo1R8tyKfgcSLhZmdWDEZS7rr31VfRhJMD5UoM2Mo0hJfediIQIx9rJljIFDLreRd5pu9awj6UCfrVOABIq1rgKGI6UZ/zrrhPvq4XRorLlIq4fQpINAGxQvVtdp2OHg0hwmeGYbOA4greU6XNM25/+fLGfEhs6bISUDrz6es6Jcfi1fXJ6GZXL04m7+Jk7b2PS1CphcKi40wIyfvYX2c856CsJ+bBBDv3yFoNvjLgDbQoXWiOtGQHvretNW1C9UYhhHB5ZgkbBN0T+rExmFdSlz/I2ba31WS/WxlKWx81xsn+pKVBVOSIi3bXEr0MGXgomtRolrBsPFnq9o8d0mA9L3ebWt/kofDkx/7yzxjx9Cf+9cF8ecE/S8=
    admin-user: AgBVBu4EewEcLR6iN2gFc66W3apG3FOKUAncpJxOq1WZaAy+WNEWNtRfQe8BS52KlQfBuo6NVaHxPqqr5RLkylatyWR/ykbCzbwCGBiXxhRxCnjBFa7FKOj6pAMjdC9eqyOCLnaI3a4TQNG3xSMPRzo4sKQUA9ADtGUSZ9VlInWV95Em7WN+QUOayPIwOpzjIPY4xlIhJFhIdPGEi1957urgJnpmnfYksW8XbDz7ixDxa4dO4OzAZnzusdA/IfPdYDT3QTpcB5Io7xWeqkARtbQTWnsXhfRLS7YBd8V5Laua5EttEaphVTeoSQBif1pUsIZCx85upbYNr1FuPwxxyvDSWFthfwwt4y1ISVEDacJR62kpdHt1ntmWfdk+9MZIFTTkof+uMLYTcmgfvBSUEDv2gTvXvFPM1WL+aJR54TmOdMSd4+ZfPN4depEpd30ROqXrS7P85eTfB1cpnMfJZU3YtVucJFWA+3zB4cIAMFwXqaUq0INKKUQ7+MU01d9SA18z+nNHtMojUwce1r3nwnQALI2pVy59SKow7Q5JgctFJsd3Ru0oyx2o8WwFXYGpEVrJ5ijWT3WDwwda3F161cCgqTeVkFASaLGkkNHMB0mp/0lhT9bp7GRV1wDp0sLrlVUmjbwEJlkph92zxzTou43Miqge5sxK+wrvk3Q3Ub+Hz1ui5aFhCzliIqf/AnzaGUfe7fR0rg==
  template:
    data: null
    metadata:
      creationTimestamp: null
      labels:
        component: grafana
      name: grafana-credentials
      namespace: customer
    type: Opaque

